version: "3"
services:
  vault:
    image: vault:1.11.3
    restart: always
    ports:
      - "8200:8200"
    environment:
      LOG_LEVEL: debug
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ./data/logs:/vault/logs
      - ./data/file:/vault/file
      - ./data/config:/vault/config
      - ./data/scripts:/vault/scripts
    cap_add:
      - IPC_LOCK
    command: >
      sh -c "vault server -config=/vault/config/vault.hcl"
  agent:
    image: vault:1.11.3
    environment:
      LOG_LEVEL: debug
      VAULT_ADDR: "http://vault:8200"
    volumes:
      - ./data/agent:/vault/agent:rw
    command: >
      sh -c "vault agent -config=/vault/agent/agent.hcl"
    depends_on:
      - vault
